Repository WildCodeSchool/orleans-0219-php-aeromodelisme, pull requests merged in 2019-04, with the labels that each got.

#1 Project init
  composer.lock
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Admin/adminlayout.html.twig
  src/View/Home/index.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/User/userlayout.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
Labels: Changes requested, Corrections done, Reviewed by PO

#2 Sprint00 us01 integration template
  public/assets/css/animate.css
  public/assets/css/style.css
  public/assets/js/main.js
  src/View/Home/index.html.twig
  src/View/adminlayout.html.twig
  src/View/base.html.twig
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#3 Suppression du JS + Clean du CSS
  public/assets/css/animate.css
  public/assets/css/style.css
  public/assets/js/main.js
  src/View/base.html.twig
Labels: Reviewed by PO

#4 Sprint00 us02 navbar
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/base.html.twig
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#6 Sprint01 us08 history
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/base.html.twig
Labels: Changes requested

#5 S00 us03 header
  composer.lock
  public/assets/css/style.css
  public/assets/fonts/Alien Robot.otf
  public/assets/fonts/Android Assassin.ttf
  public/assets/images/LogoRCMCO.gif
  public/assets/images/avion2flip.jpg
  src/View/base.html.twig
  src/View/userlayout.html.twig
Labels: Conflicts, Corrections done

#7 Intégration du widget météo
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/base.html.twig
Labels: Corrections done, Reviewed by PO

#9 Intégration de la vidéo des 40ans
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Corrections done

#12 Fix navbar sticky
  public/assets/css/style.css
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#14 Fix redirection weather
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#8 Sprint01 us07 activities
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/userlayout.html.twig
Labels: Conflicts, Corrections done

#15 Fix css
  public/assets/css/style.css
Labels: Reviewed by PO

#13 footer added to layout.html
  public/assets/css/style.css
  src/View/base.html.twig
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#17 Sprint01 us05 events
  composer.lock
  public/assets/css/style.css
  public/assets/images/events/affiche meeting.jpg
  public/assets/images/events/ailes_et_brevets.jpg
  public/assets/images/events/entretien_terrain.jpg
  public/assets/images/events/racer.jpg
  src/Controller/HomeController.php
  src/Model/EventManager.php
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#18 déplacement de la section activités
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#23 S001 us09 weather
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#26 Ajout de la page inscription
  public/assets/css/style.css
  src/Controller/InscriptionController.php
  src/View/Inscription/index.html.twig
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#27 Us21 admin navbar
  src/View/adminlayout.html.twig
Labels: Reviewed by PO

#30 Closes #29
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#25 add legal mentions page
  src/Controller/LegalController.php
  src/View/Legal/legalmentions.html.twig
  src/View/base.html.twig
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#24 Sprint02 us12 partner
  .gitignore
  public/assets/css/style.css
  src/Controller/HomeController.php
  src/Controller/InscriptionController.php
  src/Model/PartnerManager.php
  src/View/_partner.html.twig
  src/View/base.html.twig
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#35 SPRINT02_US22_CONTACT
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#39 add title in events issue#37
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#43 Sprint03 us34 admin view events
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Model/EventManager.php
  src/View/Admin/events.html.twig
  src/View/adminlayout.html.twig
Labels: Reviewed by PO

#33 Sprint01 us10 descrip activities
  composer.lock
  public/assets/css/style.css
  public/assets/images/avions/avion1.jpg
  public/assets/images/avions/avion5.jpg
  public/assets/images/avions/avion6.jpg
  public/assets/images/helico/helico1.jpg
  public/assets/images/helico/helico2.jpg
  public/assets/images/helico/helico3.jpg
  public/assets/images/indoor/indoor1.jpg
  public/assets/images/indoor/indoor2.jpg
  public/assets/images/indoor/indoor3.jpg
  public/assets/images/planeur/planeur.jpg
  public/assets/images/planeur/planeur1.jpg
  public/assets/images/planeur/planeur2.jpg
  public/assets/images/planeur/planeur3.jpg
  src/Controller/ActivitiesController.php
  src/View/Activities/index.html.twig
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#40 Sprint03 us31 gallery random
  .gitignore
  public/assets/css/style.css
  public/assets/images/LogoRCMCO.gif
  public/assets/images/avion2flip.jpg
  public/assets/images/events/ailes_et_brevets.jpg
  public/assets/images/events/entretien_terrain.jpg
  public/assets/images/events/racer.jpg
  public/assets/images/favicon.png
  src/Controller/GalleryController.php
  src/Model/GalleryManager.php
  src/View/Gallery/index.html.twig
Labels: Corrections done, Reviewed by PO

#42 FIX#41_NAVBAR_USER
  public/assets/css/style.css
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#44 Sprint03 us35 view partners
  src/Controller/AdminController.php
  src/View/Admin/partners.html.twig
Labels: Reviewed by PO

#31 page ecolage made
  public/assets/css/style.css
  public/assets/images/logo-ffam.png
  src/Controller/SchoolingController.php
  src/View/Schooling/index.html.twig
Labels: Corrections done, NOT TESTED !!! SHAME !!!!!, Reviewed by PO

#49 FIX_FONTS_#47
  public/assets/css/style.css
Labels: Reviewed by PO

#51 FIX_PARTNERS_#50
  src/Controller/ActivitiesController.php
  src/Controller/GalleryController.php
  src/Controller/InformationsController.php
  src/Controller/LegalController.php
Labels: Reviewed by PO

#53 FIX_NAVBAR_USER_#52
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#55 Sprint03 us26 admin modify events
  src/Controller/AdminController.php
  src/Model/EventManager.php
  src/View/Admin/_formevent.html.twig
  src/View/Admin/editevent.html.twig
Labels: Reviewed by PO

#61 closes #58
  src/Model/EventManager.php
Labels: Reviewed by PO

#63 SPRINT03_US32_GALLERY_ARCHIVE
  public/assets/css/style.css
  src/Controller/GalleryController.php
  src/Model/GalleryManager.php
  src/View/Gallery/index.html.twig
  src/View/Gallery/showByYear.html.twig
Labels: Reviewed by PO

#64 Fix#60 modif jumbotron
  public/assets/css/style.css
  public/assets/fonts/MilestoneFreeVersion-Script.otf
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#46 SPRINT03_US23_ADMIN_DELETE_PARTNERS
  src/Controller/AdminController.php
  src/Model/PartnerManager.php
  src/View/Admin/partners.html.twig
  src/View/adminlayout.html.twig
Labels: Corrections done, Reviewed by PO

#65 closes #62
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Changes requested, Corrections done, Reviewed by PO

#69 closes #67
  src/Controller/AdminController.php
Labels: Reviewed by PO

#66 Sprint01 us11 footer front
  .gitignore
  public/assets/css/style.css
  public/assets/images/events/affiche meeting.jpg
  src/View/Home/index.html.twig
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#72 FIX_PARTNERS_#50
  src/Controller/GalleryController.php
  src/Controller/SchoolingController.php
Labels: Reviewed by PO
