Repository WildCodeSchool/orleans-0219-php-aeromodelisme, pull requests merged in 2019-05, with the labels that each got.

#75 Fix navbar + header
  public/assets/css/style.css
  public/assets/images/LogoRCMCO.gif
  public/assets/images/big-one.jpg
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#77 Fix#71 photos activities
  public/assets/css/style.css
  public/assets/images/indoor/indoor2.jpg
  public/assets/images/indoor/indoor3.jpg
  src/View/Activities/index.html.twig
Labels: Reviewed by PO

#79 Creations et mise en forme des boutons activités
  public/assets/css/style.css
  public/assets/images/back_icone_act.png
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#68 Sprint01 us10 descrip activities
  public/assets/css/style.css
  public/assets/js/drawPlane.js
  src/View/Activities/index.html.twig
  src/View/base.html.twig
Labels: Corrections done, Reviewed by PO

#80 SPRINT03_US36_GALLERY_EVENT
  public/assets/css/style.css
  src/Controller/GalleryController.php
  src/Model/GalleryManager.php
  src/View/Gallery/index.html.twig
  src/View/Gallery/showByYearAndEvent.html.twig
Labels: Corrections done, Reviewed by PO

#76 Creation pages des membres du club
  public/assets/css/style.css
  src/Controller/MemberController.php
  src/Model/MemberManager.php
  src/View/Member/index.html.twig
  src/View/userlayout.html.twig
Labels: Corrections done, Reviewed by PO

#81 Fix weather#78
  .gitignore
  public/assets/css/style.css
  public/assets/images/avions/avion1.jpg
  public/assets/images/avions/avion5.jpg
  public/assets/images/avions/avion6.jpg
  public/assets/images/helico/helico1.jpg
  public/assets/images/helico/helico2.jpg
  public/assets/images/helico/helico3.jpg
  public/assets/images/indoor/indoor1.jpg
  public/assets/images/planeur/planeur.jpg
  public/assets/images/planeur/planeur1.jpg
  public/assets/images/planeur/planeur2.jpg
  public/assets/images/planeur/planeur3.jpg
  public/assets/images/weather/1.png
  public/assets/images/weather/10.png
  public/assets/images/weather/11.png
  public/assets/images/weather/12.png
  public/assets/images/weather/13.png
  public/assets/images/weather/14.png
  public/assets/images/weather/15.png
  public/assets/images/weather/16.png
  public/assets/images/weather/17.png
  public/assets/images/weather/18.png
  public/assets/images/weather/19.png
  public/assets/images/weather/2.png
  public/assets/images/weather/3.png
  public/assets/images/weather/4.png
  public/assets/images/weather/5.png
  public/assets/images/weather/6.png
  public/assets/images/weather/7.png
  public/assets/images/weather/8.png
  public/assets/images/weather/9.png
  public/assets/images/weather/logo2.png
  public/assets/images/weather/wind/1.png
  public/assets/images/weather/wind/2.png
  public/assets/images/weather/wind/3.png
  public/assets/images/weather/wind/33.png
  public/assets/images/weather/wind/4.png
  public/assets/images/weather/wind/5.png
  public/assets/images/weather/wind/6.png
  public/assets/images/weather/wind/7.png
  public/assets/images/weather/wind/8.png
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
Labels: Corrections done, Reviewed by PO

#84 closes#83 fix homepage style
  public/assets/css/style.css
  src/View/Home/index.html.twig
  src/View/userlayout.html.twig
Labels: Reviewed by PO

#85 FIX_PARTNERS_#50
  src/Controller/MemberController.php
Labels: Reviewed by PO

#89 closes#86 fix meteo on homepage
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed by PO

#82 cards years 2017 and 2018 add to Gallery/index
  .gitignore
  src/Controller/GalleryController.php
  src/Model/GalleryManager.php
  src/View/Gallery/index.html.twig
Labels: Changes requested, Reviewed by PO

#88 Fix btn gallery #87
  public/assets/css/style.css
Labels: Reviewed by PO

#91 FIX_TITLE_#90
  src/View/Activities/index.html.twig
  src/View/Gallery/index.html.twig
  src/View/Gallery/showByYearAndEvent.html.twig
  src/View/Informations/index.html.twig
  src/View/Member/index.html.twig
  src/View/Schooling/index.html.twig
Labels: Corrections done, Reviewed by PO

#92 Changement text btn dans galerie
  src/View/Gallery/index.html.twig
Labels: Reviewed by PO

#93 Changement couleur activités home page + background vidéo
  public/assets/css/style.css
  src/View/Home/index.html.twig
Labels: Reviewed by PO
